<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Dictionary;
use Doctrine\ORM\EntityRepository;

/**
 * DictionaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DictionaryRepository extends EntityRepository
{
    /**
     * @param $code
     *
     * @return mixed
     *
     * @throws \Doctrine\ORM\NonUniqueResultException
     * @throws \Doctrine\ORM\NoResultException
     */
    public function fetchByCode($code)
    {
        $query = $this->createQueryBuilder('d')
            ->where('p.code = :code')
            ->setParameter('code', $code)
            ->getQuery();
        return $query->getSingleResult();
    }

    /**
     * Create a dictionary
     *
     * @param Dictionary $dictionary
     */
    public function create(Dictionary $dictionary)
    {
        $this->getEntityManager()->persist($dictionary);
        $this->getEntityManager()->flush();
    }

    /**
     * Delete a dictionary
     *
     * @param Dictionary $dictionary
     */
    public function delete(Dictionary $dictionary)
    {
        $this->getEntityManager()->detach($dictionary);
        $this->getEntityManager()->flush();
    }
}
