<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;
use Knp\Component\Pager\Paginator;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{
    private $paginate;

    public function setPaginate(Paginator $paginate)
    {
        $this->paginate = $paginate;
    }

    public function fetchWordByDictionary($dictionary, $page, $limit)
    {
        $query = $this->createQueryBuilder('w')
            ->where('w.dictionary = :dictionary')
            ->setParameter('dictionary', $dictionary)
            ->getQuery();

        return $this->paginate->paginate(
            $query,
            $page,
            $limit
        );
    }
}
