services:
    app_word_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine', getRepository]
        arguments:
          - 'AppBundle:Word'
        calls:
            - method: setPaginate
              arguments:
                - '@knp_paginator'
