services:
    app_word_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine', getRepository]
        arguments:
          - 'AppBundle:Word'
        calls:
            - method: setPaginate
              arguments:
                - '@knp_paginator'
            - method: setDispatcher
              arguments:
                - '@event_dispatcher'

    app.word.invalidation_cache:
        class: AppBundle\EventListener\InvalidationCacheWordListener
        arguments:
            - '@fos_http_cache.cache_manager'
        tags:
            - { name: kernel.event_listener, event: word.created }

    app.word.dispatch_event_outside:
        class: AppBundle\EventListener\DispatchOutsideWordListener
        arguments:
            - '@old_sound_rabbit_mq.word_producer'
            - '@jms_serializer'
        tags:
            - { name: kernel.event_listener, event: word.created }
            - { name: kernel.event_listener, event: dictionary.loaded }
