version: '3'

services:
  dictionary-mysql:
    image: mysql:5.7
    container_name: dictionary-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dictionary
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - docker_some-net

  dictionary-webserver:
    image: phpdockerio/nginx:latest
    container_name: dictionary-webserver
    volumes:
        - ../:/var/www/dictionary
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8089:8080"
    environment:
      PORT: "8080"
    networks:
      - docker_some-net

  dictionary-php-fpm:
    build: ./php-fpm/
    container_name: dictionary-php-fpm
    environment:
      - JWT_PASSPHRASE=jwtmypassphrase
    volumes:
      - ../:/var/www/dictionary
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
    networks:
      - docker_some-net

  rabbit_mq:
    image: rabbitmq:3-management
    container_name: dictionary-rabbit
    ports:
      - "8010:15672"
      - "5672:5672"
      - "5671:5671"
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
      - docker_some-net

  varnish:
    image: eeacms/varnish
    container_name: dictionary-varnish
    ports:
      - "8090:6081"
    environment:
      BACKENDS: "dictionary-webserver"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      BACKENDS_PROBE_INTERVAL: "10s"
      BACKENDS_PROBE_TIMEOUT: "1s"
      BACKENDS_PROBE_WINDOW: "3"
      BACKENDS_PROBE_THRESHOLD: "2"
    networks:
      - docker_some-net

networks:
  docker_some-net:
    external: true
