dictionary-mysql:
  image: mysql:5.7
  container_name: dictionary-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=ftv
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root

dictionary-webserver:
  image: phpdockerio/nginx:latest
  container_name: dictionary-webserver
  volumes:
      - ../:/var/www/dictionary
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
   - dictionary-php-fpm
  ports:
   - "8089:8080"

dictionary-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: dictionary-php-fpm
  volumes:
    - ../:/var/www/dictionary
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.0/fpm/conf.d/99-overrides.ini
  links:
    - dictionary-mysql
